# Generated by Django 3.1.2 on 2020-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descrition',
            field=models.TextField(null=True),
        ),
    ]
